package code.webdkmh.dao.repositories;

import code.webdkmh.dao.entities.CourseOffering;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.querydsl.QuerydslPredicateExecutor;
import org.springframework.stereotype.Repository;

/**
* Generated by Spring Data Generator on 12/02/2022
*/
@Repository
public interface CourseOfferingRepository extends JpaRepository<CourseOffering, String>, JpaSpecificationExecutor<CourseOffering>, QuerydslPredicateExecutor<CourseOffering> {

}
