/*
 * Created on 2022-02-12 ( 18:57:48 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package code.webdkmh.dao.entities;

import java.io.Serializable;
import java.util.Date;
import javax.persistence.*;

/**
 * JPA entity class for "PasswordResetToken"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="password_reset_token", schema="dbo", catalog="Course_Registration" )
public class PasswordResetToken implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="ID_User", nullable=false, length=50)
    private String     idUser ;

    //--- ENTITY DATA FIELDS 
    @Column(name="token", nullable=false, length=50)
    private String     token ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="expiry_Date", nullable=false)
    private Date       expiryDate ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @OneToOne
    @JoinColumn(name="ID_User", referencedColumnName="ID_User", insertable=false, updatable=false)
    private Users      users ; 


    /**
     * Constructor
     */
    public PasswordResetToken() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setIdUser( String idUser ) {
        this.idUser = idUser ;
    }
    public String getIdUser() {
        return this.idUser;
    }

    public void setToken( String token ) {
        this.token = token ;
    }
    public String getToken() {
        return this.token;
    }

    public void setExpiryDate( Date expiryDate ) {
        this.expiryDate = expiryDate ;
    }
    public Date getExpiryDate() {
        return this.expiryDate;
    }

    //--- GETTERS FOR LINKS
    public Users getUsers() {
        return this.users;
    } 

    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(idUser);
        sb.append("|");
        sb.append(token);
        sb.append("|");
        sb.append(expiryDate);
        return sb.toString(); 
    } 

}
