/*
 * Created on 2022-02-12 ( 18:57:48 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package code.webdkmh.dao.entities;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * JPA entity class for "Professor"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name = "Professor", schema = "dbo", catalog = "Course_Registration")
public class Professor implements Serializable {

    private static final long serialVersionUID = 1L;

    // --- ENTITY PRIMARY KEY
    @Id
    @Column(name = "ID_Professor", nullable = false, length = 50)
    private String idProfessor;

    // --- ENTITY DATA FIELDS
    @Column(name = "Professor_Name", nullable = false, length = 50)
    private String professorName;

    @Column(name = "ID_Faculty", nullable = false, length = 50)
    private String idFaculty;

    @Temporal(TemporalType.DATE)
    @Column(name = "Create_date", nullable = false)
    private Date createDate;

    @Column(name = "Degree", length = 50)
    private String degree;

    // --- ENTITY LINKS ( RELATIONSHIP )
    @OneToOne
    @JoinColumn(name = "ID_Professor", referencedColumnName = "ID_User", insertable = false, updatable = false)
    private Users users;

    @OneToMany(mappedBy = "professor")
    private List<Schedule> listOfSchedule;

    @OneToMany(mappedBy = "professor")
    private List<ProfessorSchedule> listOfProfessorSchedule;

    @ManyToOne
    @JoinColumn(name = "ID_Faculty", referencedColumnName = "ID_Faculty", insertable = false, updatable = false)
    private Faculty faculty;

    /**
     * Constructor
     */
    public Professor() {
        super();
    }

    // --- GETTERS & SETTERS FOR FIELDS
    public void setIdProfessor(String idProfessor) {
        this.idProfessor = idProfessor;
    }

    public String getIdProfessor() {
        return this.idProfessor;
    }

    public void setProfessorName(String professorName) {
        this.professorName = professorName;
    }

    public String getProfessorName() {
        return this.professorName;
    }

    public void setIdFaculty(String idFaculty) {
        this.idFaculty = idFaculty;
    }

    public String getIdFaculty() {
        return this.idFaculty;
    }

    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    public Date getCreateDate() {
        return this.createDate;
    }

    public void setDegree(String degree) {
        this.degree = degree;
    }

    public String getDegree() {
        return this.degree;
    }

    // --- GETTERS FOR LINKS
    public Users getUsers() {
        return this.users;
    }

    public List<Schedule> getListOfSchedule() {
        return this.listOfSchedule;
    }

    public List<ProfessorSchedule> getListOfProfessorSchedule() {
        return this.listOfProfessorSchedule;
    }

    public Faculty getFaculty() {
        return this.faculty;
    }

    // --- toString specific method
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(idProfessor);
        sb.append("|");
        sb.append(professorName);
        sb.append("|");
        sb.append(idFaculty);
        sb.append("|");
        sb.append(createDate);
        sb.append("|");
        sb.append(degree);
        return sb.toString();
    }

}
