/*
 * Created on 2022-02-12 ( 18:57:48 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package code.webdkmh.dao.entities;

import java.io.Serializable;
import javax.persistence.*;

/**
 * JPA entity class for "UserHasRole"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name = "USER_has_role", schema = "dbo", catalog = "Course_Registration")
public class UserHasRole implements Serializable {

    private static final long serialVersionUID = 1L;

    // --- ENTITY PRIMARY KEY
    @Id
    @Column(name = "ID_User", nullable = false, length = 50)
    private String idUser;

    // --- ENTITY DATA FIELDS
    @Column(name = "ID_User_Kind", nullable = false, length = 2)
    private String idUserKind;

    // --- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne
    @JoinColumn(name = "ID_User_Kind", referencedColumnName = "ID_User_Kind", insertable = false, updatable = false)
    private UserKind userKind;

    @OneToOne
    @JoinColumn(name = "ID_User", referencedColumnName = "ID_User", insertable = false, updatable = false)
    private Users users;

    /**
     * Constructor
     */
    public UserHasRole() {
        super();
    }

    // --- GETTERS & SETTERS FOR FIELDS
    public void setIdUser(String idUser) {
        this.idUser = idUser;
    }

    public String getIdUser() {
        return this.idUser;
    }

    public void setIdUserKind(String idUserKind) {
        this.idUserKind = idUserKind;
    }

    public String getIdUserKind() {
        return this.idUserKind;
    }

    // --- GETTERS FOR LINKS
    public UserKind getUserKind() {
        return this.userKind;
    }

    public Users getUsers() {
        return this.users;
    }

    // --- toString specific method
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(idUser);
        sb.append("|");
        sb.append(idUserKind);
        return sb.toString();
    }

}
