/*
 * Created on 2022-02-12 ( 18:57:48 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package code.webdkmh.dao.entities;

import java.io.Serializable;
import java.util.List;
import javax.persistence.*;

/**
 * JPA entity class for "UserKind"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="USER_KIND", schema="dbo", catalog="Course_Registration" )
public class UserKind implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="ID_User_Kind", nullable=false, length=2)
    private String     idUserKind ;

    //--- ENTITY DATA FIELDS 
    @Column(name="Name_User_Kind", nullable=false, length=50)
    private String     nameUserKind ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @OneToMany(mappedBy="userKind")
    private List<UserHasRole> listOfUserHasRole ; 


    /**
     * Constructor
     */
    public UserKind() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setIdUserKind( String idUserKind ) {
        this.idUserKind = idUserKind ;
    }
    public String getIdUserKind() {
        return this.idUserKind;
    }

    public void setNameUserKind( String nameUserKind ) {
        this.nameUserKind = nameUserKind ;
    }
    public String getNameUserKind() {
        return this.nameUserKind;
    }

    //--- GETTERS FOR LINKS
    public List<UserHasRole> getListOfUserHasRole() {
        return this.listOfUserHasRole;
    } 

    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(idUserKind);
        sb.append("|");
        sb.append(nameUserKind);
        return sb.toString(); 
    } 

}
