/*
 * Created on 2022-02-12 ( 18:57:48 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package code.webdkmh.dao.entities;

import java.io.Serializable;
import javax.persistence.*;

/**
 * JPA entity class for "Users"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="USERS", schema="dbo", catalog="Course_Registration" )
public class Users implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="ID_User", nullable=false, length=50)
    private String     idUser ;

    //--- ENTITY DATA FIELDS 
    @Column(name="email", nullable=false, length=50)
    private String     email ;

    @Column(name="password", nullable=false, length=255)
    private String     password ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @OneToOne(mappedBy="users")
    private UserHasRole userHasRole ; 

    @OneToOne(mappedBy="users")
    private UserDetail userDetail ; 

    @OneToOne(mappedBy="users")
    private Professor  professor ; 

    @OneToOne(mappedBy="users")
    private Student    student ; 

    @OneToOne(mappedBy="users")
    private PasswordResetToken passwordResetToken ; 


    /**
     * Constructor
     */
    public Users() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setIdUser( String idUser ) {
        this.idUser = idUser ;
    }
    public String getIdUser() {
        return this.idUser;
    }

    public void setEmail( String email ) {
        this.email = email ;
    }
    public String getEmail() {
        return this.email;
    }

    public void setPassword( String password ) {
        this.password = password ;
    }
    public String getPassword() {
        return this.password;
    }

    //--- GETTERS FOR LINKS
    public UserHasRole getUserHasRole() {
        return this.userHasRole;
    } 

    public UserDetail getUserDetail() {
        return this.userDetail;
    } 

    public Professor getProfessor() {
        return this.professor;
    } 

    public Student getStudent() {
        return this.student;
    } 

    public PasswordResetToken getPasswordResetToken() {
        return this.passwordResetToken;
    } 

    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(idUser);
        sb.append("|");
        sb.append(email);
        sb.append("|");
        sb.append(password);
        return sb.toString(); 
    } 

}
