/*
 * Created on 2022-02-12 ( 18:57:48 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package code.webdkmh.dao.entities;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * JPA entity class for "UserDetail"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name = "user_detail", schema = "dbo", catalog = "Course_Registration")
public class UserDetail implements Serializable {

    private static final long serialVersionUID = 1L;

    // --- ENTITY PRIMARY KEY
    @Id
    @Column(name = "ID_User", nullable = false, length = 50)
    private String idUser;

    // --- ENTITY DATA FIELDS
    @Column(name = "address", nullable = false, length = 50)
    private String address;

    @Column(name = "phone_number", nullable = false, length = 10)
    private String phoneNumber;

    // @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "birthday", nullable = false)
    private Date birthday;

    // --- ENTITY LINKS ( RELATIONSHIP )
    @OneToOne
    @JoinColumn(name = "ID_User", referencedColumnName = "ID_User", insertable = false, updatable = false)
    private Users users;

    /**
     * Constructor
     */
    public UserDetail() {
        super();
    }

    // --- GETTERS & SETTERS FOR FIELDS
    public void setIdUser(String idUser) {
        this.idUser = idUser;
    }

    public String getIdUser() {
        return this.idUser;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getAddress() {
        return this.address;
    }

    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    public String getPhoneNumber() {
        return this.phoneNumber;
    }

    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    public Date getBirthday() {
        return this.birthday;
    }

    // --- GETTERS FOR LINKS
    public Users getUsers() {
        return this.users;
    }

    // --- toString specific method
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(idUser);
        sb.append("|");
        sb.append(address);
        sb.append("|");
        sb.append(phoneNumber);
        sb.append("|");
        sb.append(birthday);
        return sb.toString();
    }

}
