package code.webdkmh.dao.managers;

import code.webdkmh.dao.entities.BillingSystem;
import code.webdkmh.dao.repositories.BillingSystemRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 12/02/2022
*/
@Component
public class BillingSystemManager {

	private BillingSystemRepository billingSystemRepository;

	@Autowired
	public BillingSystemManager(BillingSystemRepository billingSystemRepository) {
		this.billingSystemRepository = billingSystemRepository;
	}

}
