package code.webdkmh.dao.managers;

import code.webdkmh.dao.entities.Clazz;
import code.webdkmh.dao.repositories.ClazzRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 12/02/2022
*/
@Component
public class ClazzManager {

	private ClazzRepository clazzRepository;

	@Autowired
	public ClazzManager(ClazzRepository clazzRepository) {
		this.clazzRepository = clazzRepository;
	}

}
