package code.webdkmh.dao.managers;

import code.webdkmh.dao.entities.Course;
import code.webdkmh.dao.repositories.CourseRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 12/02/2022
*/
@Component
public class CourseManager {

	private CourseRepository courseRepository;

	@Autowired
	public CourseManager(CourseRepository courseRepository) {
		this.courseRepository = courseRepository;
	}

}
