package code.webdkmh.dao.managers;

import code.webdkmh.dao.entities.Faculty;
import code.webdkmh.dao.repositories.FacultyRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 12/02/2022
*/
@Component
public class FacultyManager {

	private FacultyRepository facultyRepository;

	@Autowired
	public FacultyManager(FacultyRepository facultyRepository) {
		this.facultyRepository = facultyRepository;
	}

}
