package code.webdkmh.dao.managers;

import code.webdkmh.dao.entities.FinalResult;
import code.webdkmh.dao.repositories.FinalResultRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 12/02/2022
*/
@Component
public class FinalResultManager {

	private FinalResultRepository finalResultRepository;

	@Autowired
	public FinalResultManager(FinalResultRepository finalResultRepository) {
		this.finalResultRepository = finalResultRepository;
	}

}
