package code.webdkmh.dao.managers;

import code.webdkmh.dao.entities.FrontSub;
import code.webdkmh.dao.repositories.FrontSubRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 12/02/2022
*/
@Component
public class FrontSubManager {

	private FrontSubRepository frontSubRepository;

	@Autowired
	public FrontSubManager(FrontSubRepository frontSubRepository) {
		this.frontSubRepository = frontSubRepository;
	}

}
