package code.webdkmh.dao.managers;

import code.webdkmh.dao.entities.PasswordResetToken;
import code.webdkmh.dao.repositories.PasswordResetTokenRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 12/02/2022
*/
@Component
public class PasswordResetTokenManager {

	private PasswordResetTokenRepository passwordResetTokenRepository;

	@Autowired
	public PasswordResetTokenManager(PasswordResetTokenRepository passwordResetTokenRepository) {
		this.passwordResetTokenRepository = passwordResetTokenRepository;
	}

}
