package code.webdkmh.dao.managers;

import code.webdkmh.dao.entities.Professor;
import code.webdkmh.dao.repositories.ProfessorRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 12/02/2022
*/
@Component
public class ProfessorManager {

	private ProfessorRepository professorRepository;

	@Autowired
	public ProfessorManager(ProfessorRepository professorRepository) {
		this.professorRepository = professorRepository;
	}

}
