package code.webdkmh.dao.managers;

import code.webdkmh.dao.entities.ProfessorSchedule;
import code.webdkmh.dao.repositories.ProfessorScheduleRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 12/02/2022
*/
@Component
public class ProfessorScheduleManager {

	private ProfessorScheduleRepository professorScheduleRepository;

	@Autowired
	public ProfessorScheduleManager(ProfessorScheduleRepository professorScheduleRepository) {
		this.professorScheduleRepository = professorScheduleRepository;
	}

}
