package code.webdkmh.dao.managers;

import code.webdkmh.dao.entities.Schedule;
import code.webdkmh.dao.repositories.ScheduleRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 12/02/2022
*/
@Component
public class ScheduleManager {

	private ScheduleRepository scheduleRepository;

	@Autowired
	public ScheduleManager(ScheduleRepository scheduleRepository) {
		this.scheduleRepository = scheduleRepository;
	}

}
