package code.webdkmh.dao.managers;

import code.webdkmh.dao.entities.SemesterResult;
import code.webdkmh.dao.repositories.SemesterResultRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 12/02/2022
*/
@Component
public class SemesterResultManager {

	private SemesterResultRepository semesterResultRepository;

	@Autowired
	public SemesterResultManager(SemesterResultRepository semesterResultRepository) {
		this.semesterResultRepository = semesterResultRepository;
	}

}
