package code.webdkmh.dao.managers;

import code.webdkmh.dao.entities.Semester;
import code.webdkmh.dao.repositories.SemesterRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 12/02/2022
*/
@Component
public class SemesterManager {

	private SemesterRepository semesterRepository;

	@Autowired
	public SemesterManager(SemesterRepository semesterRepository) {
		this.semesterRepository = semesterRepository;
	}

}
