package code.webdkmh.dao.managers;

import code.webdkmh.dao.entities.StudentScheduleR;
import code.webdkmh.dao.repositories.StudentScheduleRRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 12/02/2022
*/
@Component
public class StudentScheduleRManager {

	private StudentScheduleRRepository studentScheduleRRepository;

	@Autowired
	public StudentScheduleRManager(StudentScheduleRRepository studentScheduleRRepository) {
		this.studentScheduleRRepository = studentScheduleRRepository;
	}

}
