package code.webdkmh.dao.managers;

import code.webdkmh.dao.entities.TimeForCourseRegister;
import code.webdkmh.dao.repositories.TimeForCourseRegisterRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 12/02/2022
*/
@Component
public class TimeForCourseRegisterManager {

	private TimeForCourseRegisterRepository timeForCourseRegisterRepository;

	@Autowired
	public TimeForCourseRegisterManager(TimeForCourseRegisterRepository timeForCourseRegisterRepository) {
		this.timeForCourseRegisterRepository = timeForCourseRegisterRepository;
	}

}
