package code.webdkmh.dao.managers;

import code.webdkmh.dao.entities.UserDetail;
import code.webdkmh.dao.repositories.UserDetailRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 12/02/2022
*/
@Component
public class UserDetailManager {

	private UserDetailRepository userDetailRepository;

	@Autowired
	public UserDetailManager(UserDetailRepository userDetailRepository) {
		this.userDetailRepository = userDetailRepository;
	}

}
