package code.webdkmh.dao.managers;

import code.webdkmh.dao.entities.UserKind;
import code.webdkmh.dao.repositories.UserKindRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 12/02/2022
*/
@Component
public class UserKindManager {

	private UserKindRepository userKindRepository;

	@Autowired
	public UserKindManager(UserKindRepository userKindRepository) {
		this.userKindRepository = userKindRepository;
	}

}
