package code.webdkmh.dao.managers;

import code.webdkmh.dao.entities.Users;
import code.webdkmh.dao.repositories.UsersRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 12/02/2022
*/
@Component
public class UsersManager {

	private UsersRepository usersRepository;

	@Autowired
	public UsersManager(UsersRepository usersRepository) {
		this.usersRepository = usersRepository;
	}

}
